services:

  laravel:
    image: shinsenter/laravel
    container_name: laravel
    volumes:
        - ./src_lara:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  pgsql:
    image: postgres
    container_name: pgsql
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"